server:
  port: 8004

spring:
  application:
    name: audit-listener
  datasource:
    url: jdbc:postgresql://localhost:5314/auditdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:8090
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: ryzendee.starter.audit.model
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

audit:
  kafka:
    listener:
      topic:
        methods:
          name: audit.methods
        requests:
          name: audit.requests
        errors:
          name: audit.errors
          settings:
              retry:
                interval: 1000
                max-attempts: 3